### ISSUE TITLE
Use cookie storage as an alternative to AJAX calls

### ISSUE THREAD

**Issue by kalenjordan** [fbrnc/Aoe_Static#13]
I took a brief look at the module to see whether there was any support for using cookies to store some data, in order to not have to fire an AJAX call on every page load.

It looks like jquery.cookie.js is bundled in there but the only time it's called is in a place that's commented out to store the session ID:
https://github.com/fbrnc/Aoe_Static/blob/master/js/aoestatic/common.js#L47

I was wondering if it might make sense to add cookie support.  I have some ideas on how to implement it, if so.  Let me know what you think and I'll flesh out my thoughts!

**Comment by fbrnc** [comment]
Hi Kalen,

sorry for the late reply. 

We're actually doing this already in our projects. Also there's a new shiny version in the "refactored" branch of the AOEmedia repo. Check this out: https://github.com/aoemedia/Aoe_Static/tree/refactored

**Comment by kalenjordan** [comment]
Oh cool!  I'll check that out.  Any plans to merge that into master or does it need more testing before it's stable?

**Comment by fbrnc** [comment]
We'll go live in 2 weeks with a project using that branch. If everything works well I'll consider that branch well-tested and will merge that into master :)

**Comment by kalenjordan** [comment]
:thumbsup:

**Comment by jonesio** [comment]
Any update on if you consider the refactored cookie support branch well-tested?
